### ISSUE TITLE
Allow font options to be filtered

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#12]
_From @desrosj on April 2, 2018 19:51_

The font options in `responsive_font_options()` should be filterable.

Related: #386.

_Copied from original issue: bu-ist/responsive-framework-1x#385_

**Comment by ashleykolodziej** [comment]
This is like the best idea ever for companion themes 👍

**Comment by ashleykolodziej** [comment]
This is also related to decoupling the Framework dependency on fonts licensed to bu.edu - we can't include things like Benton by default if we want to open source.

**Comment by toddmilliken** [comment]
Adding the filter is easy, no problem with that.

However, we'll need to decide what fonts should be available by default in the future when we open source if we can't offer up Benton, Capita, Tiempos, Pressura due to licensing/private use. 

We could maybe have Framework supply a list of open source fonts like Google Fonts, or remove the Font Options all together and add them in via a companion plugin that hooks into responsi to add these branding assets via the filters we're making available.
