### ISSUE TITLE
Do we still need bundler?

### ISSUE THREAD

**Issue by sr4136** [bu-ist/responsive-framework#122]
Now that we're using node-sass, instead of ruby, do we still need bundler?

**Comment by toddmilliken** [comment]
I don't believe so. I think the `bundle install` post install script is for installing the ruby gem for sass if user doesn't have it, which presents issues for users who don't have ruby installed or installed correctly with the right permissions.

I'm all for removing the Gemfile in the root of the repository, plus the postinstall script portion for `bundle install`

**Comment by toddmilliken** [comment]
Note: I think we need to update the child starter to use the same sass changes we introduced into framework, because child starter is still using the ruby gem for sass: https://github.com/bu-ist/responsive-child-starter/blob/develop/Gemfile . 

For example, @rjfoleyiv experienced several issues on `r-innovate` due to `bundle install` failing due to system permission issues/ruby path issues. 

For resolving these ruby versions, I was able to resolve the ruby path issues by installing a ruby version manager (rbenv) and removing a previous ruby version manager (rvm). I configured my machine to use a local copy of ruby (2.5.3) using `rbenv local 2.5.3` so it doesn't use the system default version, so that `bundle install` can read/write using my local copy from rbenv and not error on attempting to read/write using the system copy.

Also worth mentioning we're using `grunt-sass v2.1.0` which uses node-sass by default. If we want to update to the latest version of grunt-sass, there is a change where we must also require the sass compiler we intend to use [`node-sass`](https://github.com/sass/node-sass) or [`dart-sass`](https://github.com/sass/dart-sass) are the ones indicated in the documentation: https://github.com/sindresorhus/grunt-sass/

**Comment by toddmilliken** [comment]
#7 has more history on why we have bundler (tl;dr: its because we used to use ruby sass and something [Jon D added for code climate test coverage](https://github.com/bu-ist/responsive-framework/commit/4aa79ed26939762cb0634d3ab002483965944208#diff-8b7db4d5cc4b8f6dc8feb7030baa2478) which seems to be [deprecated](https://github.com/codeclimate/ruby-test-reporter) in place of the [new test coverage repo](https://github.com/codeclimate/test-reporter).

In summary: 
- @ashleykolodziej has done great work removing the ruby sass from Gemfile and Gemfile.lock in this repo and in [responsive-framework-1x](https://github.com/bu-ist/responsive-framework-1x/pull/407/files). All thats remaining right now is this `rspec` ruby Gem that is supposedly for the antiquated code climate test coverage tool. The new one may not need this, since there is a JavaScript implementation as well as a few others.
- Our current version of `grunt-sass` is the latest 2x version -- i have  `2.1.0` currently in my node_modules for this repo, which uses `node-sass` by default ([see grunt-sass@2.1.0](https://github.com/sindresorhus/grunt-sass/tree/v2.1.0) ). One thing to note is if we update `grunt-sass` to the [latest version on GitHub (`3.0.2` currently)](https://github.com/sindresorhus/grunt-sass), we'll have to also install either `node-sass` or `dart-sass` and tell `grunt-sass` which implementation we'd like to use. This is a future problem that doesn't need to be tackled right now, but we should if we want the latest updates from grunt-sass.

I think next steps for this are to see if we can replace code climate's `rspec` dependency which was needed for the [deprecated test coverage tool](https://github.com/codeclimate/ruby-test-reporter), and look into how we can leverage a different solution using the new [text coverage tool](https://github.com/codeclimate/test-reporter). Then we could remove `rspec` and the bundle install completely.
