### ISSUE TITLE
Add options to responsive_primary_nav() 

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-framework#132]
### Responsive Version: All

The `bu_navigation_display_primary()` function has a whole bunch of arguments that can be passed. It would be nice to expose these to the `responsive_primary_nav()` function so they can be used without having to instead directly call the `bu_navigation_display_primary()` function. 

see: https://github.com/bu-ist/bu-navigation/blob/2d252b06b59f0428753a292b7d5f636ae16c0339/includes/library.php#L964
```
function bu_navigation_display_primary( $args = '' ) {
	$defaults = array(
		'post_types' => array( 'page' ),
		'include_links' => true,
		'depth' => BU_NAVIGATION_PRIMARY_DEPTH,
		'max_items' => BU_NAVIGATION_PRIMARY_MAX,
		'dive' => true,
		'container_tag' => 'ul',
		'container_id' => 'nav',
		'container_class' => '',
		'item_tag' => 'li',
		'identify_top' => false,
		'whitelist_top' => null,
		'echo' => 1,
		'title_before' => '',
		'title_after' => '',
		);
```

**Comment by ashleykolodziej** [comment]
This is a great idea and seems like an easy pick. Let's do it!

**Comment by toddmilliken** [comment]
There is a bug that currently exists, where these arguments are overriding the settings defined in Appearance > Primary Navigation, such as `max_items` value.

Screenshot of settings that changes max_items from its default value `6` to a new value of `7`:

![screen shot 2019-03-01 at 10 08 50 am](https://user-images.githubusercontent.com/26465346/53646839-37803780-3c0a-11e9-923f-1dc5e79f6688.png)
![screen shot 2019-03-01 at 10 09 51 am](https://user-images.githubusercontent.com/26465346/53646840-37803780-3c0a-11e9-8217-749c010571ba.png)

As you can see, the settings have no effect and is still showing `6` items when the expected number should be `7` due to the updated settings that were saved.

This is due to how BU Navigation provides default arguments, then uses a filter to apply the arguments saved from settings. Then it merges that result with any arguments passed into the function, in which case is `depth` and `max_items`: https://github.com/bu-ist/responsive-framework/blob/2.1.13/inc/bu-template-tags.php#L26-L27

I have a PR coming shortly that will only override the args we need that get passed into `
bu_navigation_display_primary()`. It will still be filterable so child themes can choose to either
1. Filter Responsive Framework's arguments that are being supplied to BU Navigation using the filter defined here https://github.com/bu-ist/responsive-framework/blob/2.1.13/inc/bu-template-tags.php#L23 . This will override defaults + plugin settings.
2. Use the native filter like BU Navigation does to apply its settings: 
```
// Fires before settings have been applied.
add_filter( 'bu_filter_primarynav_defaults', 'my_theme_change_args', 1  );

// Fires after settings have been applied.
add_filter( 'bu_filter_primarynav_defaults', 'my_theme_change_args', 11  );
```
