### ISSUE TITLE
Template Tags

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#216]
Related file: `inc/template-tags.php`
- [ ] `responsive_get_the_title` Line 152: This elseif needs refactoring to remove the `bu_profile` call from the logic.  However, that logic should be move to a child theme in a way that it doesn't break functionality of this function.
- [ ] `responsive_is_bu_domain` - move to child
- [ ] `responsive_has_comment_support` - move to child
- [ ] `responsive_comments` - move to child if it is only needed in tandem with the above comment function
- [ ] `responsive_primary_nav` - refactor to move the `bu_navigation` functionality to child, leaving a hook in place to override.
- [ ] `responsive_post_meta` Line 641 - Refactor to a hook, allow `bu_supports_comments` to override the default in a child theme
- [ ] `responsive_get_posts_archive_link` Line 710: Move the news pages functionality to child, calling either a new hook or the existing filter
- [ ] `responsive_profiles_archive_link` - move to child
- [ ] `responsive_get_footbar_id` move to chi

**Comment by mustafauysal** [comment]
**responsive_get_the_title**: filtering through`responsive_get_the_title` seems a good plan

**responsive_is_bu_domain**: move into the child theme - this is a bit risky to move mu-plugins since the old framework has the same function. We need to move icon functionalities to child theme rather than mu-plugins too. #29 

**responsive_has_comment_support**: instead of moving this to child theme, we can apply a filter and make the customizations in the child theme. E.g `apply_filter('responsive_has_comment_support', get_default_comment_status());`

**responsive_comments**: leave it as it

**responsive_primary_nav**: I don't see `bu_navigation` in place - I think this is already resolved.

**responsive_post_meta**: we can fire `responsive_post_meta_before` and `responsive_post_meta_after` actions and move the existing functionality to child theme. 

**responsive_get_posts_archive_link**: move news pages functionality to child theme and filter with `responsive_get_posts_archive_link`

**responsive_profiles_archive_link**:  move into the child theme if we are ok with removing the function call in `single-profile.php`  - If the order of the output is not necessary, we can hook it to `r_before_closing_article` action inside the child theme.

**responsive_get_footbar_id**: keep the function in the framework but remove `post_type_supports( $post->post_type, 'bu-dynamic-footbars' ) ` and BU specific functionalities in `responsive_theme_supports_dynamic_footbars`

@ashleykolodziej What are your thoughts? Essentially, we can keep the functions in place and apply BU specific changes with the child theme.

**Comment by ashleykolodziej** [comment]
I think this makes sense. I'm going to walk through this with two example sites, using `responsive_is_bu_domain`:

- bu.edu/bands, which uses Responsive Framework directly right now
- bu.edu/dining, which uses a custom child theme of Responsive Framework right now

So in this scenario, instead of using Responsive Framework directly, bu.edu/bands would use a child theme of Responsive Framework, and bu.edu/dining would use a different child theme of Responsive Framework that is based off the original child theme, but heavily customized. 

`responsive_is_bu_domain` is needed for both those themes, so keeping it in the child theme would mean that code would need to be duplicated, right? Is there a way that we can share this type of code between child themes so it doesn't get duplicated?

**Comment by mustafauysal** [comment]
@ashleykolodziej that's a good point. Actually `bu.edu/dining` is not using `responsive_is_bu_domain`. However,  keeping the customizations in a separate plugin would be much better. I will continue on that route.
