### ISSUE TITLE
BU Access Control

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#233]
**Related plugins**
- https://github.com/bu-ist/bu-access-control
- https://github.com/bu-ist/bu-access-control-bumc-additions

**Templates**
- [ ] `no-access-bumc.php` https://github.com/bu-ist/responsive-framework/blob/develop/no-access-bumc.php
- [ ] `no-access.php` https://github.com/bu-ist/responsive-framework/blob/develop/no-access-bumc.php

**Comment by mustafauysal** [comment]
@thrijith It seems these template files are only used in https://github.com/bu-ist/bu-access-control-bumc-additions/blob/master/www.bumc.bu.edu/bumc.php#L165-L171 

I think we can address this task in two ways;
1) Move templates to custom plugin and update `TEMPLATEPATH`
2) Move templates and `set_audience()` functionality to custom plugin - https://github.com/bu-ist/bu-access-control-bumc-additions/blob/master/www.bumc.bu.edu/bumc.php#L23 (private methods need to updated)

Both solutions are ending up with the updating https://github.com/bu-ist/bu-access-control-bumc-additions plugin.

@ashleykolodziej  Thoughts?

**Comment by ashleykolodziej** [comment]
I think we should go with 1 because it will involve the least disruption to the access control plugin - I'm super wary of removing anything from that. Besides that, I don't think anyone in the history of ever has overridden the BUMC access control template, so it makes sense to me to just put that back in the access control plugin where it belongs. :)

**Comment by thrijith** [comment]
Option 1 is a better choice, as it involves less changes, moving the templates to the mu-plugin would make it loose theme specific styling etc, so what we can do is, check if the template exits for `bu-responsive-customizations` then load it, else keep the current behaviour as it is.

@ashleykolodziej Please let me know if that sounds ok?

**Comment by ashleykolodziej** [comment]
@thrijith Sounds great :D

**Comment by thrijith** [comment]
@ashleykolodziej I checked the option to include the plugin template, since the change is in mu-plugin it loads before our plugin is initialised, so I think the check should go in opposite way.

E.g check if a template exists in theme path, if yes then load that, else check if plugin template exists, if yes then load that. 

The issue with loading from plugin path is, the option to override that template can only be done if theme adds its own templates in theme root at same path as it is in the 2x right now.
