### ISSUE TITLE
BU Profiles - Sidebars

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#234]
**Related plugin:** https://github.com/bu-ist/bu-profiles

- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/sidebar-profiles.php

**Comment by mustafauysal** [comment]
@thrijith It seemed that sidebar is called with `get_sidebar( 'profiles' )` in
* https://github.com/bu-ist/responsive-framework/blob/2e8568994f84bdd7e4a7a7ac3c93bd9f163696f1/archive-profile.php#L66
* https://github.com/bu-ist/responsive-framework/blob/2e8568994f84bdd7e4a7a7ac3c93bd9f163696f1/profiles.php#L66
* https://github.com/bu-ist/responsive-framework/blob/2e8568994f84bdd7e4a7a7ac3c93bd9f163696f1/single-profile.php#L170

I think we can print that out by using `r_before_closing_container_inner` action within the custom plugin. 

cc/ @ashleykolodziej

**Comment by ashleykolodziej** [comment]
Yup, this makes sense to me 👍

**Comment by thrijith** [comment]
@ashleykolodziej I'll add changes for this along with https://github.com/bu-ist/responsive-framework/issues/236, as they are related closely, also instead of hooking into `r_before_closing_container_inner` and checking the page template conditionally, can we use the same implementation as calendar for sidebar? [ref](https://github.com/bu-ist/bu-responsive-customizations/pull/11/files#diff-aa83a16796003c3301fde130ec309828R69)

**Comment by ashleykolodziej** [comment]
@thrijith Yes, absolutely! I'd definitely rather grab a template part. 👍
