### ISSUE TITLE
Move BU specific functions out of header

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#29]
@anton-kachurin brought up a good point - `responsive_is_bu_domain` probably has a better home somewhere else as we think about open sourcing. My personal opinion: it looks like it'd be a great addition to BU Branding. Can this be added with a new action hook or something existing in WordPress instead?

Doing this should allow us to remove `bu_meta` as well.

https://github.com/bu-ist/responsive-framework/blob/5651b9f53293c3743186bb23e8c8be6120740123/header.php#L22-L32

**Comment by mustafauysal** [comment]
@ashleykolodziej I think we should keep header.php minimal. It can be extendible with `wp_head` hook. 

**Meta tags:** Move meta tags to post details plugin

**Icon:** I don't think it's necessary to keeping icon tags in the framework. WordPress 4.3+ support site icons and automatically adds icon meta tags. In order to keep old behavior, I'd move the `shortcut link` to branding plugin by checking  -  `( ! has_site_icon() && ! responsive_is_bu_domain() )`

**Default Icon:** we can move it to the branding plugin.

https://github.com/bu-ist/responsive-framework/blob/5651b9f53293c3743186bb23e8c8be6120740123/header.php#L36
(This could conflict with the site-icon when it set via the customizer)

Summarizing;
* When site-icon set through customizer, don't use framework-specific icons.
* Use [BU icons](https://github.com/bu-ist/responsive-framework/blob/develop/icons/apple-touch-icon-precomposed.png) on bu_domains
* Use [global icon](https://raw.githubusercontent.com/bu-ist/responsive-framework/develop/icons/favicon-g.ico) when the fw running outside of bu_domain

thoughts?

**Comment by ashleykolodziej** [comment]
This is perfect and exactly what we want to do. Let’s do it! 💯
