### ISSUE TITLE
Can `grunt update_lightgallery` actually update lightgallery?

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#70]
_From @ashleykolodziej on April 4, 2018 14:55_

### Actual behavior: This command doesn't update the package

When I first ran `grunt update_lightgallery`, I expected it to fetch any new lightgallery updates and update the version numbers automatically. However, in this documentation, the command only handles updating version numbers. https://github.com/bu-ist/responsive-framework-documentation/blob/2x-documentation/tasks/Upgrading-jQuery-lightGallery-in-the-Framework.md

If it's possible to get grunt to send npm commands, it'd be really nice to have it check for updates in this command so all you have to do is run this command to do all the steps involved in updating lightgallery. If the Modernizr command works the same way, we may want to explore doing something similar there.

_Copied from original issue: bu-ist/responsive-framework-1x#390_

**Comment by toddmilliken** [comment]
We've refactored some JS. Moving forward I think the best way to update lightgallery is like any other dependency, and then run the copy task.

1. Update version `package.json` manually or run `npm update lightgallery` to get the latest allowed version according to package.json semver.
2. Run `grunt copy:lightgallery` to copy the node module's css, fonts, and images into the theme.

The version of lightgallery used in Framework is defined here in `package.json` https://github.com/bu-ist/responsive-framework/blob/develop/package.json#L76  . You could see the latest version at the plugin GitHub repo https://github.com/sachinchoolur/lightGallery/blob/master/package.json#L3 or you can see the latest version at the NPM repo https://www.npmjs.com/package/lightgallery

Ideally we'd migrate away from this plugin, because we shouldn't need to load separate css, fonts, and images for a lightgallery plugin. If anything, maybe just some css but not fonts and images.

**Comment by ashleykolodziej** [comment]
Quick question then - what is the purpose of the `update_lightgallery` command? Maybe there's a better name for what this does we can use?

**Comment by toddmilliken** [comment]
It should be used the same way as `grunt copy:lightgallery` except it also updates the constants in the functions file.

Really what should happen is this line https://github.com/bu-ist/responsive-framework/blob/develop/Gruntfile.js#L398 needs to be changed to 
```
		'copy:lightgallery',
```

So the workflow would be like this:
1. Update version package.json manually or run npm update lightgallery to get the latest allowed version according to package.json semver.
2. Run `grunt update_lightgallery` function to kick off re-copying the latest assets from the package in node_modules to the theme, and then it will also update the constants in Framework to use the package.json values of that package.

**Comment by ashleykolodziej** [comment]
Todd is right, this can be handled by npm.
